name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev libatlas-base-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker build -t my-dash-app .

      - name: Log in to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo "$HF_TOKEN" | docker login --username ${{ secrets.HF_USERNAME }} --password-stdin huggingface.co

      - name: Push Docker image to Hugging Face
        run: |
          docker tag my-dash-app huggingface.co/${{ secrets.HF_USERNAME }}/recomendaciones_yelp:latest
          docker push huggingface.co/${{ secrets.HF_USERNAME }}/recomendaciones_yelp:latest
